/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as arenaFighterSol from "./ArenaFighter.sol";
export * as arenaGameSol from "./ArenaGame.sol";
export * as arenaMarketplaceSol from "./ArenaMarketplace.sol";
export { ArenaCoin__factory } from "./ArenaCoin__factory";
