/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arenaFighterSol from "./ArenaFighter.sol";
export type { arenaFighterSol };
import type * as arenaGameSol from "./ArenaGame.sol";
export type { arenaGameSol };
import type * as arenaMarketplaceSol from "./ArenaMarketplace.sol";
export type { arenaMarketplaceSol };
