/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IArenaFighter,
  IArenaFighterInterface,
} from "../../../contracts/ArenaGame.sol/IArenaFighter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "recordLoss",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "recordWin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "stats",
    outputs: [
      {
        internalType: "uint8",
        name: "strength",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "speed",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "intelligence",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "rarity",
        type: "uint8",
      },
      {
        internalType: "uint32",
        name: "wins",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "losses",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "mintedAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IArenaFighter__factory {
  static readonly abi = _abi;
  static createInterface(): IArenaFighterInterface {
    return new Interface(_abi) as IArenaFighterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IArenaFighter {
    return new Contract(address, _abi, runner) as unknown as IArenaFighter;
  }
}
