/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ArenaGame__factory } from "./ArenaGame__factory";
export { IArenaCoin__factory } from "./IArenaCoin__factory";
export { IArenaFighter__factory } from "./IArenaFighter__factory";
