/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ArenaGameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "arenaCoin"
      | "battleCooldown"
      | "battleCount"
      | "battlePvE"
      | "battlePvP"
      | "battles"
      | "fighterNFT"
      | "lastBattleTime"
      | "owner"
      | "pveWinReward"
      | "pvpWinReward"
      | "renounceOwnership"
      | "setBattleCooldown"
      | "setPveWinReward"
      | "setPvpWinReward"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BattleResolved" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "arenaCoin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "battleCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "battleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "battlePvE",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "battlePvP",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "battles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fighterNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastBattleTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pveWinReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pvpWinReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBattleCooldown",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPveWinReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPvpWinReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "arenaCoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "battleCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "battleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "battlePvE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "battlePvP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "battles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fighterNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastBattleTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pveWinReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pvpWinReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBattleCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPveWinReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPvpWinReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BattleResolvedEvent {
  export type InputTuple = [
    battleId: BigNumberish,
    attackerTokenId: BigNumberish,
    defenderTokenId: BigNumberish,
    outcome: BigNumberish,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    battleId: bigint,
    attackerTokenId: bigint,
    defenderTokenId: bigint,
    outcome: bigint,
    reward: bigint
  ];
  export interface OutputObject {
    battleId: bigint;
    attackerTokenId: bigint;
    defenderTokenId: bigint;
    outcome: bigint;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArenaGame extends BaseContract {
  connect(runner?: ContractRunner | null): ArenaGame;
  waitForDeployment(): Promise<this>;

  interface: ArenaGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  arenaCoin: TypedContractMethod<[], [string], "view">;

  battleCooldown: TypedContractMethod<[], [bigint], "view">;

  battleCount: TypedContractMethod<[], [bigint], "view">;

  battlePvE: TypedContractMethod<
    [attackerTokenId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  battlePvP: TypedContractMethod<
    [attackerTokenId: BigNumberish, defenderTokenId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  battles: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, bigint, bigint, bigint] & {
        attackerTokenId: bigint;
        defenderTokenId: bigint;
        attacker: string;
        defender: string;
        mode: bigint;
        outcome: bigint;
        reward: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  fighterNFT: TypedContractMethod<[], [string], "view">;

  lastBattleTime: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pveWinReward: TypedContractMethod<[], [bigint], "view">;

  pvpWinReward: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBattleCooldown: TypedContractMethod<
    [cooldown: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPveWinReward: TypedContractMethod<
    [reward: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPvpWinReward: TypedContractMethod<
    [reward: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "arenaCoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "battleCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "battleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "battlePvE"
  ): TypedContractMethod<
    [attackerTokenId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "battlePvP"
  ): TypedContractMethod<
    [attackerTokenId: BigNumberish, defenderTokenId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "battles"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, bigint, bigint, bigint] & {
        attackerTokenId: bigint;
        defenderTokenId: bigint;
        attacker: string;
        defender: string;
        mode: bigint;
        outcome: bigint;
        reward: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fighterNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastBattleTime"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pveWinReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pvpWinReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBattleCooldown"
  ): TypedContractMethod<[cooldown: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPveWinReward"
  ): TypedContractMethod<[reward: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPvpWinReward"
  ): TypedContractMethod<[reward: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BattleResolved"
  ): TypedContractEvent<
    BattleResolvedEvent.InputTuple,
    BattleResolvedEvent.OutputTuple,
    BattleResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BattleResolved(uint256,uint256,uint256,uint8,uint256)": TypedContractEvent<
      BattleResolvedEvent.InputTuple,
      BattleResolvedEvent.OutputTuple,
      BattleResolvedEvent.OutputObject
    >;
    BattleResolved: TypedContractEvent<
      BattleResolvedEvent.InputTuple,
      BattleResolvedEvent.OutputTuple,
      BattleResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
