/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IArenaFighterInterface extends Interface {
  getFunction(
    nameOrSignature: "ownerOf" | "recordLoss" | "recordWin" | "stats"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordLoss",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordWin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stats", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordLoss", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordWin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stats", data: BytesLike): Result;
}

export interface IArenaFighter extends BaseContract {
  connect(runner?: ContractRunner | null): IArenaFighter;
  waitForDeployment(): Promise<this>;

  interface: IArenaFighterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  recordLoss: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordWin: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  stats: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        strength: bigint;
        speed: bigint;
        intelligence: bigint;
        rarity: bigint;
        wins: bigint;
        losses: bigint;
        mintedAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "recordLoss"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordWin"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stats"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        strength: bigint;
        speed: bigint;
        intelligence: bigint;
        rarity: bigint;
        wins: bigint;
        losses: bigint;
        mintedAt: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
