/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArenaGame } from "./ArenaGame";
export type { IArenaCoin } from "./IArenaCoin";
export type { IArenaFighter } from "./IArenaFighter";
