/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ArenaFighter__factory } from "./ArenaFighter__factory";
export { IArenaCoin__factory } from "./IArenaCoin__factory";
